import os
import logging
import pandas as pd
from flask import Flask, request, jsonify, render_template
from supabase import create_client, Client
import mlflow.pyfunc

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
 
 
app = Flask(__name__)

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
logging.info("Connected to Supabase")

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI")
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI )
model_uri = "models:/DTRegressor/latest" #Call "DTRegressor" by the name of "Models" on MLFlow
model = mlflow.pyfunc.load_model(model_uri)
logging.info("Connected to MLFlow")

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods = ['POST'])
def predict():
    try:
        data = request.get_json()
        df = pd.DataFrame([{
            "MedInc" : float(data['MedInc']),
            'HouseAge' : float(data['HouseAge']),
            "AveRooms" : float(data['AveRooms']),
            "AveBedrms" : float(data['AveBedrms']),
            "Population": float(data["Population"]),
            "AveOccup": float(data["AveOccup"]),
            "Latitude": float(data["Latitude"]),
            "Longitude": float(data["Longitude"])
        }])
        prediction = model.predict(df)

        #As sklearn always returns an array/list, so the price is like ["4.134"] -> use [0] to remove the [] (takes the value of the list)
        prediction = float(prediction[0])*100000 

        #orients = records is to convert pandas df into a list of dictionary, [0] to remove the []
        payload = df.to_dict(orient='records')[0]
        payload["predicted_price"] = prediction #Create a new pair in the payload dict

        #Gotta create a new table manually on Supabase first (SQL editor)
        """"
            CREATE TABLE "Manual_production_logs" (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            "MedInc" FLOAT,
            "HouseAge" FLOAT,
            "AveRooms" FLOAT,
            "AveBedrms" FLOAT,
            "Population" FLOAT,
            "AveOccup" FLOAT,
            "Latitude" FLOAT,
            "Longitude" FLOAT,
            "predicted_price" FLOAT
            );
        """
        supabase.table("Manual_production_logs").insert(payload).execute()
        

        return jsonify({
            "status": "success",
            "predicted_price_usd": prediction
        }), 200
    
    except Exception as e:
        logging.error(f"Loi xu ly Request: {str(e)}")

        return jsonify({
            "status": "error",
            "message": str(e)
        }), 500

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)